<Project Sdk="Microsoft.NET.Sdk">

	<ItemGroup>
		<PackageReference Include="BCrypt.Net-Next" Version="4.0.3" />
		<PackageReference Include="MailKit" Version="4.3.0" />
		<PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="8.0.0" />
		<PackageReference Include="MiniWord" Version="0.9.2" />
		<PackageReference Include="System.IdentityModel.Tokens.Jwt" Version="8.0.0" />
		<PackageReference Include="itext7" Version="7.2.5" />
		<ProjectReference Include="..\HRMS.Domain\HRMS.Domain.csproj" />
		<ProjectReference Include="..\HRMS.Application\HRMS.Application.csproj" />
		<PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="8.0.0" />
		<PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="8.0.0">
			<PrivateAssets>all</PrivateAssets>
			<IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
		</PackageReference>
	</ItemGroup>



	<PropertyGroup>
		<TargetFramework>net8.0</TargetFramework>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
	</PropertyGroup>

</Project>
